name: Test Bun sh

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: bun_sh/install-bun-sh@main
      - name: Test Bun sh
        run: |
          bun sh --version
