name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2.5.0

    - name: Set up bun.sh
      run: |
        curl -fsSL https://bun.sh/install | bash -s -- -v latest
        source "$HOME/.bun/bun.sh"

    - name: Run bun.sh version
      run: bun version
